(require 'quicklisp)

(ql:quickload "cffi")
(ql:quickload "gsll")
(ql:quickload "alexandria")
(ql:quickload "iterate")
(ql:quickload "antik")
(ql:quickload "closer-mop")
(ql:quickload "cl-csv")
(ql:quickload "cl-fad")
(ql:quickload "external-program")
